name: Status Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run every day at 6 AM UTC
    - cron: '0 6 * * *'

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
    - name: Check repository status
      run: |
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref }}"
        echo "Commit: ${{ github.sha }}"
        echo "Actor: ${{ github.actor }}"
        echo "Event: ${{ github.event_name }}"
        
    - name: System info
      run: |
        echo "Runner OS: ${{ runner.os }}"
        echo "Runner Architecture: ${{ runner.arch }}"
        echo "GitHub Workspace: ${{ github.workspace }}"